Repository andreysdrv/middle.game.praktikum.yandex, pull requests merged in 2023-05, with the labels that each got.

#4 Feature/tgg 14
  .github/pull_request_template.md
  README.md
  docker-compose.yml
  packages/client/.prettierignore
  packages/client/jest.config.js
  packages/client/src/api/AuthApi.ts
  packages/client/src/assets/images/signinPageBg.png
  packages/client/src/assets/images/signupPageBg.png
  packages/client/src/client.d.ts
  packages/client/src/hooks/useFormWithValidation.ts
  packages/client/src/pages/Login/Login.tsx
  packages/client/src/pages/Login/login.module.css
  packages/client/src/utils/apiErrorsHandler.ts
  packages/client/src/utils/constants.ts
  packages/client/src/utils/validationRegExps.ts
Labels: Регистрация и авторизация

#15 Feature/tgg 18
  packages/client/src/components/App/App.tsx
  packages/client/src/pages/Landing/Landing.tsx
  packages/client/src/pages/Register/Register.tsx
  packages/client/src/pages/Register/register.module.css
  packages/client/src/utils/validationRegExps.ts
Labels: Регистрация и авторизация

#10 Feature/tgg 19
  packages/client/src/pages/Leaderboard/Leaderboard.tsx
Labels: Лидерборд

#9 tgg-16 верстка страницы форума
  packages/client/package.json
  packages/client/src/pages/Forum/Forum.tsx
  packages/client/src/pages/Forum/const.ts
  packages/client/src/pages/Forum/forum.module.css
Labels: Форум

#17 Feature/tgg 23
  packages/client/src/index.css
  packages/client/src/pages/Game/Game.tsx
  packages/client/src/pages/Game/styles.module.scss
Labels: Представление игры

#12 Feature/tgg 13
  packages/client/public/notFoundPage/notFound.svg
  packages/client/public/serverErrorPage/serverError.svg
  packages/client/src/pages/Landing/styles.module.scss
  packages/client/src/pages/NotFound/NotFound.tsx
  packages/client/src/pages/ServerError/ServerError.tsx
  packages/client/src/pages/ServerError/styles.module.scss
Labels: Базовые компоненты

#13 Механика игры на Canvas API
  packages/client/src/game/Enemy.ts
  packages/client/src/game/Player.ts
  packages/client/src/game/Tank.ts
  packages/client/src/game/View.ts
  packages/client/src/game/World.ts
  packages/client/src/game/config.ts
  packages/client/src/layouts/Main/Main.tsx
  packages/client/src/layouts/Main/styles.module.scss
  packages/client/src/pages/Game/Game.tsx
Labels: Игровой движок, ready for review

#8 Feature/tgg 12
  package-lock.json
  packages/client/src/components/App/App.test.tsx
  packages/client/src/components/UI/Avatar/Avatar.tsx
  packages/client/src/pages/Game/styles.module.scss
  packages/client/src/pages/Landing/Landing.tsx
  packages/client/src/pages/Landing/styles.module.scss
  yarn.lock
Labels: Представление игры, ready for review

#6 Feature/tgg 21
  packages/client/src/pages/Profile/ChangePasswordModal.tsx
  packages/client/src/pages/Profile/ChangeProfileModal.tsx
  packages/client/src/pages/Profile/Profile.tsx
  packages/client/src/pages/Profile/UserDataBlock.tsx
  packages/client/src/pages/Profile/UserStatBlock.tsx
  packages/client/src/pages/Profile/avatar.jpg
  packages/client/src/pages/Profile/const.tsx
  packages/client/src/pages/Profile/images/profile-background.svg
  packages/client/src/pages/Profile/profile.module.css
  packages/client/src/pages/Profile/types.ts
Labels: Профиль, ready for review

#22 feat(TGG-38): визуальная часть игры
  packages/client/src/assets/images/enemy.png
  packages/client/src/assets/images/player.png
  packages/client/src/game/Bullet.ts
  packages/client/src/game/Enemy.ts
  packages/client/src/game/Player.ts
  packages/client/src/game/Tank.ts
  packages/client/src/game/World.ts
  packages/client/src/game/config.ts
  yarn.lock
Labels: Игровой движок

#21 feat(TGG-36): Игровая механика
  packages/client/src/game/Enemy.ts
  packages/client/src/game/World.ts
  packages/client/src/game/config.ts
  packages/client/src/pages/Game/Game.tsx
  packages/client/src/pages/Game/GameEnumProps.ts
  packages/client/src/utils/getRandomNumber.ts
Labels: Игровой движок
